### ISSUE TITLE
Better Chatbot RNN for OS Support

### ISSUE THREAD

**Issue by rekkisomo** [radwolfdev/marshmallow#2]
Currently, TensorFlow is only available on 3.5.x on Windows. This causes issues as changes were made to python since 2.7.10 which would be a hassle to upgrade.

Currently testing different versions with different techniques.
![rnn-example-python3](https://i.imgur.com/DMeA2Do.png)
(Thanks to Etienne Pot for base)

**Comment by Miwrzezl** [comment]
For now though: People can just use [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/about).

**Comment by rekkisomo** [comment]
I'm no longer working on Marshmallow. If someone does not have a MacOS System they can use WSL, as stated above.

Feel free to comment on this issue if you have a strong understanding with **either** of the following: (Obviously, a strong understanding on how RNN's work is needed)
- Python & Tensorflow 
- NodeJS (hassle)
- Java (limited use with Node)

On top of this, I don't think others apart of the Radwolf team will be working on Marshmallow. You can contact me on discord via Curtis#0708 if you want to take over this project, we'll discuss more from there.

*Don't get me wrong, It's been fun making Marshmallow. If you are deciding to take over Marshmallow, I wish you best of luck :). Thanks to everyone who used Marshmallow, even the users who's been there ever since Marshmallow wasn't even named Marshmallow! Those people should have a role on the Discord Server.*
